const skillset=[
    {
        name:"NODE JS",
        icon:"images/node-js.svg",
        link:"https://nodejs.org/"
    },
    {
        name:"ANGULAR JS",
        icon:"images/angular.png",
        link:"https://angularjs.org/"
    },
    {
        name:"REACT JS",
        icon:"images/react.png",
        link:"https://reactjs.org/"
    },
    {
        name:"NEXT JS",
        icon:"images/nextjs.png",
        link:"https://nextjs.org/"
    },
    {
        name:"GIT",
        icon:"images/git.svg",
        link:"https://git-scm.com/"
    },
    {
        name:"GITHUB",
        icon:"images/github.svg",
        link:"https://github.com/"
    },
    {
        name:"MONGODB",
        icon:"images/mongodb.png",
        link:"https://www.mongodb.com/"
    },
    {
        name:"SQL",
        icon:"images/sql.jpeg",
        link:"https://www.mysql.com/"
    },
    {
        name:"PYTHON",
        icon:"images/python.png",
        link:"https://www.python.org/"
    },
    {
        name:"FIGMA",
        icon:"images/figma.png",
        link:"https://www.figma.com/"
    },
    {
        name:"NETLIFY",
        icon:"images/netlify.jpeg",
        link:"https://www.netlify.com/"
    },
    {
        name:"VERCEL",
        icon:"images/vercel.png",
        link:"https://vercel.com/"
    },
    {
        name:"CANVA",
        icon:"images/canva.jpeg",
        link:"https://www.canva.com/en_in/"
    },
    {
        name:"FLUTTER",
        icon:"images/flutter.png",
        link:"https://flutter.dev"
    },
    {
        name:"MATERIAL UI",
        icon:"images/mui.png",
        link:"https://mui.com/material-ui/"
    },
    {
        name:"FIREBASE",
        icon:"images/firebase.png",
        link:"https://firebase.google.com/"
    },
    {
        name:"THREE JS",
        icon:"images/threejs.png",
        link:"https://threejs.org"
    },
    {
        name:"A-FRAME",
        icon:"images/aframe.jpg",
        link:"https://aframe.io"
    },
    {
        name:"SELENIUM",
        icon:"images/selenium.jpg",
        link:"https://www.selenium.dev/"
    },
    {
        name:"TENSORFLOW",
        icon:"images/tensorflow.png",
        link:"https://www.tensorflow.org/"
    },
    {
        name:"SOCKET IO",
        icon:"images/socket-io.svg",
        link:"https://socket.io/"
    },
    {
        name:"FLASK",
        icon:"images/flask.png",
        link:"https://flask.palletsprojects.com/en/2.2.x/"
    }
]

export default skillset